<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <title>Music Theory Query</title>

        <!-- add metadata later *****
        <meta name="description" content="The html5 Herald">
        <meta name="author" content="SitePoint"> -->

        <link rel="stylesheet" href="MTQ.CSS">
        <script type="text/javascript" src="MTQ.JS"></script>

    </head>

    <body>
        <!-- header div hosts logo image and navbar-->
        <div id="header">
            <div id="logoContainer">
                <a href="home.php"><img src="logo stuff/logo.PNG" id="logo"></a>
            </div>

            <div id="navbar">
                <a class="navlinks" href="home.PHP">Home</a>
                <a class="navlinks" href="tunings.PHP">Tunings</a>
                <a class="navlinks" href="scales.PHP">Scales</a>
                <a class="navlinks" href="intervals.PHP">Interval Calculator</a>
                <a class="navlinks" href="chords.PHP">Chord Builder</a>
                <a class="navlinks" href="">Account</a>
            </div>
        </div>

        <!-- *** page content begins here *** -->
        <div id="content">
            <p>Welcome to Music Theory Query, the interactive music theory practice resource! You can use the navigation bar above to check out each page on the website. 
            If you would like to make an account with us, you will be able to save practice resources to this page, and customize it to suit your practice needs! Click 
            the 'Account' button on the right of the navigation bar to get started or log in.</p>
        </div>
    </body>

</html>